server:
  port: 8081
spring:
  application:
    name: SCHOOL-SERVICE
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure.include=*
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
