server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eiakoji-me/smsws
          delete-untracked-branches: true
          search-paths: 'config-service/configs'
          default-label: main
          repos:
            feature:
              pattern:
                - 'feature*'
              uri: https://github.com/eiakoji-me/smsws
              default-label: feature/working-with-config-server
              search-paths: 'config-service/configs'
            develop:
              pattern:
                - 'develop'
              uri: https://github.com/eiakoji-me/smsws
              default-label: develop
              search-paths: 'config-service/configs'
            stage:
              pattern:
                - 'stage'
              uri: https://github.com/eiakoji-me/smsws
              default-label: stage
              search-paths: 'config-service/configs'
            local:
              pattern:
                - 'local'
              uri: file:${LOCAL_CONFIGSVC_ROOT}/config-service
              default-label: feature/working-with-config-server
              search-paths: 'config-service/configs'
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      probes:
#        enabled: true
#      show-details: always
#    configprops:
#      enabled: true
#  info:
#    env:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
