server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eiakoji-me/smsws-configs
          delete-untracked-branches: true
          default-label: main
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      probes:
#        enabled: true
#      show-details: always
#    configprops:
#      enabled: true
#  info:
#    env:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
